title: "実践を意識したiOSアプリ設計の技術"

summary: "iOSが誕生してから10年以上が経過し、現在では設計や開発の複雑化が進んでいる。
この進化に伴い、単なる動作するコードを書くことを超え、可読性やデバックの容易性、そしてスケーラビリティを意識した開発が求められている。
本書では、iOSアプリ開発における設計の基本と、その考え方を体系的に整理し、開発現場に対応するための基盤を構築することを目指している。"

topics: ["ios", "swift", "uikit"]

published: false

price: 0

# チャプターの見出しを表示する深さ
toc_depth: 1
